### ISSUE TITLE
Gotcha: HTTP_X_FORWARDED_FOR returns multiple IP addresses

### ISSUE THREAD

**Issue by eternaldensity** [django-pci/django-axes#101]
The get_ip function (which uses HTTP_X_FORWARDED_FOR by default if BEHIND_REVERSE_PROXY) doesn't work in all cases.  Sometimes, HTTP_X_FORWARDED_FOR returns a string containing multiple values (for example, '127.0.0.1, 192.30.252.129').
To fix this, I changed get_ip line 73 to: 
```
    return ip.split(', ')[-1]
```
A related article about this gotcha:
http://www.jamescrowley.co.uk/2007/06/19/gotcha-http-x-forwarded-for-returns-multiple-ip-addresses/

**Comment by camilonova** [comment]
https://github.com/django-pci/django-axes/blob/master/axes/decorators.py#L86
It's done.
Thank you.
