### ISSUE TITLE
Is there a better way to implement axes.watch_login?

### ISSUE THREAD

**Issue by AJRenold** [django-pci/django-axes#102]
I'm working with both [django-two-factor-auth](https://github.com/Bouke/django-two-factor-auth) and django-axes and I'm curious if there is a better way to implement the logic found in watch_login, then inspecting the response object

https://github.com/django-security/django-axes/blob/a2860d287fbeca846f53993a808d75bcf33386eb/axes/decorators.py#L310
```python
        if request.method == 'POST':
            # see if the login was successful
            login_unsuccessful = (
                response and
                not response.has_header('location') and
                response.status_code != 302
            )
```
The problem that occurs with django-two-factor-auth is that the response object for the verification code entry page looks no different then a failed logic attempt. It is not a redirect, so the response code is 200, and it also does not have a 'location' header. I tried fixing this on a fork, but was not successful yet.

Any advice?

**Comment by jedie** [comment]
I work on my https://github.com/jedie/django-secure-js-login/ project...

IMHO you can just check ```request.user.is_authenticated()``` the the login was successful.

btw. the auth app fires also signals, see: https://docs.djangoproject.com/en/1.7/ref/contrib/auth/#topics-auth-signals

**Comment by camilonova** [comment]
I was thinking while ago to use signals, seems the perfect opportunity.

**Comment by AJRenold** [comment]
As @jedie mentioned, my solution to this was to use signals

```python
from django.contrib.auth.signals import user_logged_in
from axes.utils import reset

def clear_access_attempt_failures(sender, user, request, **kwargs):
    """
        Because django-axes does not fully support two_factor, we need to clear
        the failed login attempts for a user once they successfully log in
    """
    reset(username=user.username)

user_logged_in.connect(clear_access_attempt_failures)
```

**Comment by toabi** [comment]
How did you configure axes to watch over the two-factor login? Somehow I don't get it to work.

**Comment by camilonova** [comment]
I just moved away from Middleware. This specific behaviour can be done using signals.
