### ISSUE TITLE
middleware problem

### ISSUE THREAD

**Issue by codefisher** [django-pci/django-axes#107]
The middleware will redecorate the `auth_views.login` function on every single request.  That is why you need the `if func.__name__ == 'decorated_login':` inside the watch_login.  You should rather do this check inside the middleware, or better, add the watch_login wrapper somewhere else.  I don't see a reason it needs to be in middleware at all?

**Comment by teeberg** [comment]
We just ran into "maximum recursion depth" errors in testing for that reason. I've proposed a PR to fix this.

**Comment by camilonova** [comment]
Thank you
