### ISSUE TITLE
Support AJAX logins

### ISSUE THREAD

**Issue by shaib** [django-pci/django-axes#114]
Hi,

We're using django-axes in a one-page application where login is performed as an AJAX request. We've run into two deficiencies:

1) There is no good way to return a JSON response when the user is locked. We have used the template response to return JSON content, but it returns with the wrong type.

2) There is no way at all to extract the username from the response -- Axes only looks for it in form fields, so the blocking uses only the IP address (which is bad, many of our users are in groups behind NAT).

**Comment by camilonova** [comment]
Could you elaborate a PR to fix those issues?

**Comment by shaib** [comment]
I'll see if I can work up something, wanted to make sure the idea is acceptable first.

**Comment by camilonova** [comment]
Is done.

**Comment by markddavidoff** [comment]
@sumansai14 There is a way to do this now with the `AXES_USERNAME_CALLABLE` where u can specify how to get the username from the request.
