### ISSUE TITLE
The Documentation of AXES_USE_USER_AGENT is Written in Opposition

### ISSUE THREAD

**Issue by ybbarng** [django-pci/django-axes#117]
Hello, thank you for your awesome project. I needed such Brute Force defence and I found your project. It is great and fit exactly my need.
Before start the report, talk to you my environment. I installed your project via pip, the version is 1.3.9, and I read your README from [the github main page of the project](https://github.com/django-pci/django-axes).

I think there is a wrong description therefore report it. My English is poor, so please check I got it right.

Your document says that :
AXES_USE_USER_AGENT: If True, lock out / log based on an IP address AND a user agent. This means requests from different user agents but from the same IP are treated differently. Default: False

I think this description says next situation will be shown:
Set AXES_LOGIN_FAILURE_LIMIT = 3
Set AXES_USE_USER_AGENT = True
Try failure login with username 'A' two times.
Next Try failure login with username 'B' two times.
The server not block the ip or username because they are attempt less than AXES_LOGIN_FAILURE_LIMIT.

But when I tried, the ip is blocked and the block is not considered the username.
After that, I changed the value of AXES_USE_USER_AGENT to False and I can found the upper situation is made. It looks like in opposite operation to the documentation.
Would you check this please?

**Comment by aclark4life** [comment]
Hi @ybbarng. There are no active django-axes developers at the moment, but if you'd like to send a pull request we will consider merging.

**Comment by camilonova** [comment]
@ybbarng You can start by replicating your scenario in a test, check https://github.com/django-pci/django-axes/blob/master/axes/tests.py and add it there. If the test don't pass and should, let me know so I can fix it.

**Comment by tarkatronic** [comment]
@ybbarng I don't believe this bug report is accurate. The confusion seems to be with the term "user agent". In this case, user agent means the web browser's identification string. This setting behaves like:

* Set `AXES_USE_USER_AGENT = True`
* Set `AXES_LOGIN_FAILURE_LIMIT = 3`
* Fail 2 login attempts in Chrome
* Fail 2 login attempts in Firefox
* The IP is not blocked, because the web browser (user agent) is different

I believe what you are looking for is `AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True`.

**Comment by ybbarng** [comment]
Oh I see. I mistook the 'User Agent' for the 'User Account.' I am sorry for false issuing. Thank you for your correction.
