### ISSUE TITLE
Not locking anymore

### ISSUE THREAD

**Issue by sergiolepore** [django-pci/django-axes#124]
I've noticed that between 1.3.9 and 1.4.0, `axes.decorators.get_user_attempts` is not working as expected. After lots of failed logins, it's not returning any attempt and not locking the account.

I think I've found where is the problem:
- [1.3.9](https://github.com/django-pci/django-axes/blob/4a7b90e98e07d667c33d3996c6628036f3edf5b1/axes/decorators.py#L237)
- [1.4.0](https://github.com/django-pci/django-axes/blob/b73e659acc155dd9a69ccc22b6021ac355746f2d/axes/decorators.py#L241)

My settings:
```python
# django-axes
AXES_LOGIN_FAILURE_LIMIT = 2
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_LOCKOUT_TEMPLATE = 'layouts/marketingsite/account_locked.html'
```

If I change the `trusted=True` condition, everything works as usual:

```python
# axes/decorators.py
attempts = AccessAttempt.objects.filter(
    ip_address=ip, username=username, trusted=False
)
```

Any ideas?

**Comment by aclark4life** [comment]
@sergiolepore can we verify that conditional statement OK? E.g. `` if not attempts and not LOCK_OUT_BY_COMBINATION_USER_AND_IP:`` looks OK to me.

**Comment by sergiolepore** [comment]
Yeah, the thing is... What is the role of `trusted`? 
[Here](https://github.com/django-pci/django-axes/blob/b73e659acc155dd9a69ccc22b6021ac355746f2d/axes/decorators.py#L231-L246):

- `USE_USER_AGENT` is False (not configured in my settings file), so

```python
if USE_USER_AGENT:
    # ...
else:
    attempts = AccessAttempt.objects.filter(
        ip_address=ip, username=username, trusted=True
    )
```

- With `trusted=True`, the above query returns nothing (even after lots of failed logins), so

```python
if not attempts and not LOCK_OUT_BY_COMBINATION_USER_AND_IP:
```

- I've `LOCK_OUT_BY_COMBINATION_USER_AND_IP=True`, the last query never runs and...

```python
return attempts
```

Which is `[]`

:confused:

**Comment by aclark4life** [comment]
@sergiolepore Ah! OK well if someone can send a PR I'll cut a new release else let me know what you think we should do. Thanks

**Comment by sergiolepore** [comment]
I'll be glad to fix this issue, but I'm not quite sure which lines should I change... Anyways, I'll give it a try.

Thanks!

**Comment by iyuan** [comment]
i got the similar problem:  if not set LOCK_OUT_BY_COMBINATION_USER_AND_IP, when locked,by the same ip but  other username not login yet.looks like locked the ip .if  set LOCK_OUT_BY_COMBINATION_USER_AND_IP, locked not work.  @sergiolepore 's solution is work for me.  and my other try:
def is_user_lockable(request):
    """Check if the user has a profile with nolockout
    If so, then return the value to see if this user is special
    and doesn't get their account locked out
    """
    try:
        field = getattr(User, 'USERNAME_FIELD', 'username')
        kwargs = {
            field: request.POST.get(USERNAME_FORM_FIELD)
        }
        ###add None user valid
        if not kwargs[field]:
            return False
        ####
        user = User.objects.get(**kwargs)
    except User.DoesNotExist:
        # not a valid user
        return Tru

**Comment by AFioca** [comment]
@aclark4life It looks like this issue was fixed with 4a926c7cc6d1d203202baea885f1f232e2e6ae9f but was then reverted here 2dfcf969d88f4277f6cba2d59c755dcbe5775f8d by @camilonova. What was the reason for reverting the changes?

**Comment by camilonova** [comment]
@AFioca broken tests

**Comment by AFioca** [comment]
Ah okay I see, thanks @camilonova! Since it looks like fixing this issue has stalled, I created a pull request #125 as an attempt to solve this issue. Let me know what you think, I'd be happy to make revisions or explain my choices if needed. :)

**Comment by camilonova** [comment]
Thank you all.

**Comment by AFioca** [comment]
@camilonova or @aclark4life would you be willing to cut a new release with the merged changes?

**Comment by aclark4life** [comment]
Sure, done! https://pypi.python.org/pypi/django-axes/1.5.0

**Comment by AFioca** [comment]
Thanks, you rock!
