### ISSUE TITLE
Improvements to axes.decorators.query2str

### ISSUE THREAD

**Issue by tarkatronic** [django-pci/django-axes#127]
Scanning through the code, I noticed that this method had the following note: `The length of the output is limited to max_length to avoid a DoS attack.`

If performance is a legitimate concern in this method due to potential DoS attack, I noticed a couple of issues with the implementation.

I ran a few tests using the Python `timeit` module. Using a dictionary containing 10,000 items and iterating over the call to query2str() 1,000 times I got an average over 3 runs of 5.70709357833645 seconds. By removing the `[:max_length]` limiter, I got an average over 3 runs of 5.64547695267053 seconds. This difference is somewhat negligible, and could be written off to me running this on a busy machine.

Now, for one first-pass optimization, I moved the `[:max_length]` limiter, changing the line from `return '\n'.join(kvs)[:max_length]` to `return '\n'.join(kvs[:max_length])`; limiting the number of items before the join. With this change, I got an average of 5.573779275335255 seconds over 3 runs. But, there is one more big optimization to be made here: list comprehensions.

Switching to a list comprehension, I was able to get an average of 5.097600340998421 seconds over 3 runs. Now, while 0.6 seconds doesn't seem like a whole lot, keep in mind that this is one thousand iterations with dictionaries containing ten thousand keys. Increasing the number of iterations or size of the dictionary, this gap would widen significantly. If this method is a true concern, I think this would be a worthwhile change.

The test code follows:

```python
import timeit

setup = """
import six

PASSWORD_FORM_FIELD = 'password'

def query2str(items, max_length=1024):
    kvs = []
    for k, v in items:
        if k != PASSWORD_FORM_FIELD:
            kvs.append(six.u('%s=%s') % (k, v))

    return '\\n'.join(kvs)[:max_length]

dict = {x: x for x in range(0, 10000)}
"""

timeit.timeit('query2str(dict.items())', setup, number=1000)


setup = """
import six

PASSWORD_FORM_FIELD = 'password'

def query2str(items, max_length=1024):
    return '\\n'.join([six.u('%s=%s' % (k, v)) for k, v in six.iteritems(items) if k != PASSWORD_FORM_FIELD][:max_length])
dict = {x: x for x in range(0, 10000)}
"""
timeit.timeit('query2str(dict)', setup, number=1000)
```

Note that this also moves the iteration inside `query2str()` method and uses the Python 2/3 compatible `six.iteritems()` instead of just calling `request.POST.items()` and `request.GET.items()` outside.

**Comment by camilonova** [comment]
@tarkatronic Looks great, send a PR

**Comment by tarkatronic** [comment]
Reading over #73, it looks like this changes the proposed behavior ever so slightly. Where that is meant to limit the overall size of saved data, this limits the number of elements which can be saved.

I was able to handle both scenarios by changing the line to:

```python
    return '\\n'.join([six.u('%s=%s' % (k, v)) for k, v in six.iteritems(items) if k != PASSWORD_FORM_FIELD][:int(max_length/2)])[:max_length]
```

This takes approximately the same amount of time, and achieves the improvement requested in #73. If that approach works for you, I'll send a PR right over.

Additionally of note, I just tested this in Python 2.7.9 (my previous tests were all in 3.4.3) and found that the difference in timing is even more pronounced, as 2.x is just that much slower.

**Comment by tarkatronic** [comment]
I'd also like to add Python 3.4 and Django 1.8.5 to the testing matrix, if you've got no problem with that.

**Comment by camilonova** [comment]
@tarkatronic please go ahead

**Comment by tarkatronic** [comment]
@camilonova This is finished in #129 now, along with a few notes on the implementation

**Comment by camilonova** [comment]
Thank you.
