### ISSUE TITLE
X-Forwarded-For parsing is incorrect

### ISSUE THREAD

**Issue by jdunck** [django-pci/django-axes#132]
The [logic](https://github.com/django-pci/django-axes/blob/e56906b76682258904ffd96f2f9d2a42105fa592/axes/decorators.py#L104) currently uses the first non-private IP on the left.  But X-Forwarded-For can be forged, and the left-most value in that header might not be trustworthy.

    For the purposes of parsing the X-Forwarded-For header,
    we need to know possible proxy IPs for the chain of custody to 
    establish the real client IP.

    The left-most values of X-Forwarded-For can be forged by the attacker.
    The correct IP, for cooldown purposes, is the first non-proxy IP from the right.

    (X-Forwarded-For intends to have the client IP be the left-most, but our proxies (and trust)
     gets added to the right, forming a chain-of-trust to the left, with the last value we really got
     in the original IP header just before the first proxy.)

    e.g. A malicious client ends:
     X-Forwarded-For: some.patsy.ip
    Our proxy receives the request from malicious.ip and adds:
     X-Forwarded-For: some.patsy.ip, malicious.ip
    and sends the request on to our upstream(s) with Remote-Addr as the first proxy address.
    If we have multiple proxies, then it extends to:
     X-Forwarded-For: some.patsy.ip, malicious.ip, proxy1.ip
    and so on.

    So the X-Forwarded-For header should only be trusted if Remote IP is a proxy IP.

    If it is, then the first IP from the right, excluding our proxy IPs, is the original IP.

**Comment by camilonova** [comment]
@jdunck Hi Jeremy, can you elaborate a fix for it?

**Comment by tarkatronic** [comment]
@jdunck I'm curious, what's the source for that citation?
I had noticed, and was slightly concerned as well about, the X-Forwarded-For parsing.

I wonder if it might be worth implementing parsing along the lines of [django-ipware](https://github.com/un33k/django-ipware)? I would be curious if there are any negative implications of that particular implementation. Or if, perhaps, it's simply overkill.

**Comment by jdunck** [comment]
@tarkatronic There's not a formal doc for X-Forwarded-For, but there is an analogous Forwarded header documented here:
https://tools.ietf.org/html/rfc7239

The chain format is described in section 7.5, and the problem of header validity in 8.1.  

I infer that the semantics of the order are the same as in X-Forwarded-For, based on section 7.4, which describes how to adapt an existing X-Forwarded-For header to the RFC's Forwarded header.

I haven't looked at -ipware enough to be confident, but the [extensive header fallback](https://github.com/un33k/django-ipware/blob/45e177389a1727f24303e25f457bc67306471fd4/ipware/defaults.py#L6) it uses seems dangerous... basically any header can be forged unless an upstream has explicitly set it.  It seems to me that getting the IP has to be dependent on the deployed topology.

**Comment by jdunck** [comment]
Ah, I think I might have given the impression that I was quoting an authoritative doc with my block quote... sorry about that.  No, the blockquote is just a docstring from my own implementation... which I wrote based on the RFC I just linked. :)

**Comment by camilonova** [comment]
So it is possible for us to have an implementation of it?

**Comment by tarkatronic** [comment]
@jdunck So, thinking on this, do you think it would make sense to have some sort of setting indicating the number of proxy IPs to shed from the right hand?

I would rather not have to specify my proxy IPs specifically as, in my particular case, using AWS, I don't know the IPs of my ELBs and they could potentially change at any time.

So for example, let's say we have a setting, `AXES_PROXY_DEPTH = 2`, indicating that the app is behind two proxies which will append to X-Forwarded-For, we could then use the second IP from the right in the chain. If it's set to 1, we use the far-right IP, and if it's 0, indicating that the app is not behind a proxy, we ignore the header altogether.

Thoughts? (I'm absolutely willing to hear that this is a crap idea.)

**Comment by jdunck** [comment]
@tarkatronic I think depth would work.  Another alternative is to us [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation) but I'm not sure if cloud providers generally document the expected address spaces?

**Comment by tarkatronic** [comment]
@jdunck I could see the reason for using CIDR, but I think it might be slightly overly complex for this case, and also decrease app portability somewhat. Unless you're worried about agents behind your proxies tampering with the header... in which case you've got other issues.

Would you be interested in working up this implementation? If not, I'm sure I could make some time for it.

**Comment by ferrix** [comment]
@jdunck I made a library for digging the proxy depth up. However in case of django-axes, it does not make sense to give the user a chance to try out a password when something has already been spoofed. So you could try this separately https://github.com/codetry/xff/ before any authentication middlewares.

**Comment by camilonova** [comment]
@jdunck @tarkatronic are we going somewhere with this, or should I close this issue for now?

**Comment by camilonova** [comment]
I'll close this for now.
