### ISSUE TITLE
Improvement suggestion: Iterate over ip addresses only once

### ISSUE THREAD

**Issue by annp89** [django-pci/django-axes#133]
In https://github.com/django-pci/django-axes/blob/master/axes/decorators.py#L109, a list of ```ips``` is created by stripping whitespace from the result of ```x_forwarded_for.split(',')```.

I think this can be rewritten like so:
```
else:
    for ip_raw in x_forwarded_for.split(','):
        ip = ip_raw.strip()
        ...
```
Thoughts? If ok, I can create a pull request with this isolated change.

**Comment by camilonova** [comment]
Sure man, please send the PR. Thanks.
