### ISSUE TITLE
no migration files

### ISSUE THREAD

**Issue by ibaguio** [django-pci/django-axes#135]
I've used django-axes in a django app running 1.6, when I migrated to 1.8 couple of weeks ago, one trouble im having is an error when running `python manage.py migrate` due to the fact that axes doesn't contain any **migrations/** directory containing migration files. Im using **django-axes 1.3.9** I also didn't see any **migrations/** file in other versions of axes (correct me if im wrong with this one)

It is easy for me to fix this problem. I can just create the migrations for axes by running 
```bash
python manage.py makemigrations axes
```

Though it would be nice if the migration files was included when the application is installed, this might save some debugging time for other developers when this issue occurs to them.

**Comment by camilonova** [comment]
@ibaguio can you create a Pull Request with those files?

**Comment by ibaguio** [comment]
@camilonova will do.

**Comment by camilonova** [comment]
Thank you.

**Comment by ibaguio** [comment]
no problem
