### ISSUE TITLE
DB indexes missing on AccessAttempt

### ISSUE THREAD

**Issue by Schweigi** [django-pci/django-axes#137]
The model `AccessAttempt` does not contain any DB indexes. If this table contains a lot of entries then the login performance is very slow. I saw it already happen with 50K+ entries.

The following fields should have an index to prevent performance issues:
- user_agent
- ip_address
- username
- trusted

See `decorators.py:_get_user_attempts`: https://github.com/django-pci/django-axes/blob/master/axes/decorators.py#L229-L235

**Comment by camilonova** [comment]
Will you make a PR solving it?

**Comment by Schweigi** [comment]
Yes, I can. 

I plan to just add four individual `db_index=True` to the data model. It would also be possible to use a composite index over all four of them but I think it's to restrictive in case someone like's to filter by only one of those fields. What do you think?

**Comment by camilonova** [comment]
I agree is too restrictive.

Don't forget to add the migration as well.

**Comment by Schweigi** [comment]
I opened a PR. 

Btw. the current axes migration files are not supported by South (Django 1.5/1.6). The following article explains how to support both: http://treyhunner.com/2014/03/migrating-to-django-1-dot-7. I'm not sure if it would make sense to have both or just require user of Django < 1.5/1.6 to build the migration files manually by running a South `schemamigration`.

**Comment by aclark4life** [comment]
The only thing that makes sense to me is releasing new versions of django-axes with support for >=1.8 (i.e. Django migrations only.) :smile:

**Comment by camilonova** [comment]
:+1:
