### ISSUE TITLE
Allow overriding of watch_login decorator

### ISSUE THREAD

**Issue by mcgeeco** [django-pci/django-axes#139]
Hi. Great package. The criteria that watch_login uses to check for successful logins is very narrow. It doesn't work with REST Framework for example, or [this](https://github.com/django-pci/django-axes/issues/102). 
Wouldn't it be great to have a setting like AXES_CUSTOM_WATCH_LOGIN_DECORATOR or something that would let us write our own and easily switch it in?

**Comment by camilonova** [comment]
@mcgeeco would you like to elaborate a PR ?

**Comment by mcgeeco** [comment]
Sure! I'll try to get some time in the next few days.

**Comment by mcgeeco** [comment]
Actually when I thought about it a bit more, the decorator is pretty easy to override elsewhere, either in the middleware or urls.py. This just overrides the login success check.

Something like this: https://github.com/django-pci/django-axes/pull/140
Sorry it's messy, just wanted to give an idea.
