### ISSUE TITLE
Migrations in Python3

### ISSUE THREAD

**Issue by ideallical** [django-pci/django-axes#142]
In the old migrations some fields were prefixed with b'
In a Python3 environment this resulted into:

    You have unapplied migrations; your app may not work properly until they are applied.
    Run 'python manage.py migrate' to apply them.

Because Python3 wants to remove those b' prefixes.
I changed it in my fork, however, I suspect that on a Python2.x environment you'll get the same error message if you would use my Py3 fork with a Django version lower than 1.7

https://code.djangoproject.com/ticket/22564

**Comment by camilonova** [comment]
The ticket is fixed, can you elaborate a fix like that for this?

**Comment by ideallical** [comment]
I'd like to see the outcome of travis first btw. I used Python 2.7.10 with Django==1.7 and Python 3.5 with Django==1.9.3 and both work with this patch. Meaning no more questions of Django that says: "You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them."
