### ISSUE TITLE
Broken migrations for projects using Django 1.7 and below

### ISSUE THREAD

**Issue by votaguz** [django-pci/django-axes#165]
Since support for migrations were included in Django 1.7, projects with previous version of Django can't use this package. The reason is an import in migration 0001. 

The following error appears when you try to run ```./manage.py migrate``` in a project with Django 1.5.4

````
/python2.7/site-packages/axes/migrations/0001_initial.py", line 4, in <module>
    from django.db import migrations, models
ImportError: cannot import name migrations
````
https://github.com/django-pci/django-axes/blob/1.6.0/axes/migrations/0001_initial.py#L4

**Comment by camilonova** [comment]
1.7 and bellow is not supported, please take this in consideration the official version support: https://www.djangoproject.com/download/

**Comment by votaguz** [comment]
Then please update the package documentation. 
https://github.com/django-pci/django-axes/blob/master/README.rst#requirements 

````
django-axes requires Django 1.5 or later. The application is intended to work around the
Django admin and the regular django.contrib.auth login-powered pages.
````

**Comment by camilonova** [comment]
Done. Thanks.
