### ISSUE TITLE
User specific max login attempts

### ISSUE THREAD

**Issue by graingert** [django-pci/django-axes#63]
At the moment there is a global login failure limit:

`AXES_LOGIN_FAILURE_LIMIT`

it would be better if it were per user so that a user.

Eg. everywhere it's used:

`getattr(user_obj, "login_failure_limit", settings.AXES_LOGIN_FAILURE_LIMIT)`

the particular use case we have is:

```python
class MyUser(AbstractUser):
     ...
     @property
     def login_failure_limit(self):
        if not self._login_failure_limit:
            self._login_failure_limit = self.site_profiles_set.order_by('-login_failure_limit').values_list('login_failure_limit', Flat=True))[0]
        return self._login_failure_limit
```

**Comment by camilonova** [comment]
I'll close this for now. If someone want to send a PR you are welcome.
