### ISSUE TITLE
Possible Denial of Service with POST request data

### ISSUE THREAD

**Issue by peterkuma** [django-pci/django-axes#73]
django-axes logs POST data of login requests in full. This allows a potentialy large amount of data to be logged in the database.

How to reproduce:

    dd if=/dev/urandom of=bigfile bs=1M count=1
    curl -F 'file=<bigfile' http://localhost:8000/admin/ # See note.

The model instance in AccessAttempts now contains the full content of the file. This can be misused to fill the disk space, or slow down the browser when viewing the model instance page (esp. Firefox does not handle it very well).

django-axes should only log a limited amount of POST data, e.g. 1 kB.

**Note:** For this to work, CSRF needs to be disabled, e.g. with:

example/settings.py:

    MIDDLEWARE_CLASSES = (
        ...
        'middleware.DisableCSRF',
    )

example/middleware.py:

    class DisableCSRF(object):
        def process_request(self, request):
            setattr(request, '_dont_enforce_csrf_checks', True)

**Comment by camilonova** [comment]
Closing this in favor of #127
