### ISSUE TITLE
Inaccurate logout times with multiple sessions by the same user

### ISSUE THREAD

**Issue by yscumc** [django-pci/django-axes#87]
The behavior for tracking a user's log out time needs to be updated to account for multiple sessions by the same user.

Currently, when a user logs out, the most recent `AccessLog` row has its `logout_time` set to the current time. (See https://github.com/django-security/django-axes/blob/1.3.6/axes/signals.py#L26-L33)

However, if there are multiple sessions open, this simple logic may set the incorrect record.

### Possible solution
A `session_key` field could be added to `AccessLog` to allow tracking of the login session in `watch_login`. Then the logout signal handler should look up the correct `AccessLog` row using `session_key`.

**Comment by camilonova** [comment]
Sounds reasonable, can you elaborate a PR?

**Comment by yscumc** [comment]
Hi,

I haven't looked at this issue in over two years but I just briefly checked the source for the latest version, this still seems to be an issue.

**Comment by camilonova** [comment]
Cool, can you please help us elaborating a PR ?

**Comment by yscumc** [comment]
Unfortunately, I'm not working on integrating django-axes with our project anymore and currently don't have the time to do a PR.

If I get a chance to come back to this, I'll open a PR.
