### ISSUE TITLE
Add Captcha Option For Lockouts

### ISSUE THREAD

**Issue by pnovotnak** [django-pci/django-axes#91]
Add a configuration option to do as many large sites do- force the user to pass a captcha when they are locked out, instead of locking the user out from the site entirely

**Comment by 7wonders** [comment]
Finally got around to implementing this. It is actually very easy using https://github.com/mbi/django-simple-captcha

First change axes to lockout url - AXES_LOCKOUT_URL = '/locked'

Add the url - url(r'^locked/$', locked_out, name='locked_out'),

Create a captcha form

```
class AxesCaptchaForm(forms.Form):
    captcha = CaptchaField()
```

Create a captcha view for the above url that resets on captcha success and redirects.

```
def locked_out(request):
    if request.POST:
        form = AxesCaptchaForm(request.POST)
        if form.is_valid():
            ip = get_ip_address_from_request(request)
            reset(ip=ip)
            return HttpResponseRedirect(reverse_lazy('signin'))
    else:
        form = AxesCaptchaForm()

    return render_to_response('locked_out.html', dict(form=form), context_instance=RequestContext(request))
```

Add a captcha template

```
<form action="." method="post">
            {% csrf_token %}

            {{ form.captcha.errors }}
            {{ form.captcha }}

            <div class="form-actions">
                <input type="submit" value="Submit" />
            </div>
        </form>
```

Done!

**Comment by camilonova** [comment]
@7wonders Thank you.
