### ISSUE TITLE
Release Django 1.7 version

### ISSUE THREAD

**Issue by camilonova** [django-pci/django-axes#98]
Test and ship a version supporting django 1.7

**Comment by nicktimko** [comment]
Any ETA on getting a 3.x compatible version onto PyPI?

**Comment by aclark4life** [comment]
@nicktimko Please open a new issue to address Python 3 compat

**Comment by camilonova** [comment]
Seems django-axes is working fine with Django 1.7.

If anyone found any issue please open a new ticket.

**Comment by RafaelOrtiz** [comment]
This is happening again on a fesh installation of django 1.8, I have to temporable disable axes from INSTALLED_APPS

**Comment by aclark4life** [comment]
@RafaelOrtiz What is happening again?

**Comment by RafaelOrtiz** [comment]
@aclark4life :  /django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "axes_accessattempt" does not exist
LINE 1: ... "axes_accessattempt"."failures_since_start" FROM "axes_acce...

It could be a matter of just erasing access tables and syncdb...but not sure if there is another more elegant solution.

**Comment by seperman** [comment]
@RafaelOrtiz Are you sure it is not the same issue as in <https://github.com/django-pci/django-axes/issues/106> ?

**Comment by RafaelOrtiz** [comment]
@seperman  sure, this is something like an initial migration not happening, curiously is does not happen when you add django-axes after having a working  project. to reproduce I just reinstalled a project that in its settings has axes configurations on a complete new db and new virtualenv.

**Comment by RafaelOrtiz** [comment]
I found the root cause of this error, I had a wrong settings that was preventing to reach the axes migration, after this error was solved i re run the project and it worked without problems.
